# site settings
title: 
subtitle: 
email: gianroccolazzari@protonmail.com
description: Computational Scientist | Outdoor passionate
baseurl: "/mysite" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
# author:
# street_address: 
# city: Lasuanne
# state: 
# zip_code: 
# country: Switzerland
# phone: 

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 3

# social settings
# 500px_url:
# facebook_url:
github_url: https://github.com/ggrrll
# gitlab_url: 
# googleplus_url: 
# instagram_url: https://instagram.com
linkedin_url: https://www.linkedin.com/in/gianroccolazzari
# pinterest_url:
# slack_url:
twitter_url: https://twitter.com/gianroccolzz
google_scholar: https://scholar.google.com/citations?user=DYC1LN8AAAAJ&hl=en

# build settings
markdown: kramdown

sass:
  style: compressed
